name: LobbySystem
version: ${project.version}
main: me.maximilian1021.main.Main
api-version: 1.16
authors: [ Maximilian1021 ]
description: Steuert gewisse Funktionen in der Lobby
website: https://max1021.de

commands:
  Spawn:
    description: Teleportiert dich zum Spawn